### ISSUE TITLE
DFD Comments Feb 13

### ISSUE THREAD

**Issue by germonprez** [bubbawelshy/3420ISQA#5]
See comments: 

1) 
<img width="43" alt="screen shot 2017-02-13 at 2 35 20 pm" src="https://cloud.githubusercontent.com/assets/656208/22902153/ba09cf2a-f1f9-11e6-8089-df68adab3cc5.png">

This return arrow does not need to be there

2) Can you get the developer to also do a License and Vulnerability Request -- like the Manager 

3) CRUD Policy is pretty big. You might want to think about breaking that up into processes for (1) request policy and (2) new and update policy. 

MG

**Comment by bubbawelshy** [comment]
![screen shot 2017-02-15 at 11 01 12 am](https://cloud.githubusercontent.com/assets/25064783/22985493/3a06602e-f36e-11e6-82e7-2eae2d91495e.png)
