### ISSUE TITLE
DFD Comments Feb 15

### ISSUE THREAD

**Issue by germonprez** [bubbawelshy/3420ISQA#6]
1) NIST Results should be named Vulnerability Results 
2) You mention both NIST Results and Vulnerability Results but they are the same thing 

Looking good.

**Comment by bubbawelshy** [comment]
![screen shot 2017-02-20 at 10 33 03 am](https://cloud.githubusercontent.com/assets/25064783/23133818/1638be7e-f758-11e6-80b6-298139a42b98.png)
