### ISSUE TITLE
L&V results

### ISSUE THREAD

**Issue by bubbawelshy** [bubbawelshy/3420ISQA#7]
Does the management process need to send License and Vulnerabilities results back to the developer if the developer can access the L&V database through a separate process?

**Comment by germonprez** [comment]
Yes, it still should. I think that there are two processes in this: 

1) Management process that sends back information based on a single uploaded software package
2) A DB Query process that a manager or developer can use to query the database, irrespective of any software package upload.

**Comment by bubbawelshy** [comment]
![screen shot 2017-02-20 at 2 23 25 pm](https://cloud.githubusercontent.com/assets/25064783/23140624/37b9b1e6-f778-11e6-87e3-2e90c765c311.png)
